name: ai-analitik

services:
  ai-analitik:
    build: .
    container_name: ai-analitik
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
